language: node_js
node_js:
- '0.11'
- '0.10'
install:
- npm install
script:
- npm test
env:
  global:
  - secure: X5pEvq3Ht1DFgQ/QR+3FilMuGQ48KXSsZlXg6PX2o6pCPJFukCn7TI+a20f4m/96T7wZpeTqw3BRGJHynselJZ4urhSEeQiwBq82Xhobg7KSxk19qIEE4mT94sh6UR7z9dCowFCoEM13/NzeJFWy/vV7lHZWrxMIYof4Qipjdo8=
  - secure: ZZkqslIZuo+zCNNRFqK5Cv9vIx9maxHuQo2P58l8HcqQy91uZ7D2D4/gFfEcFpeA8k/ovPo9RnuS0HjMDBbQRJ9ZBeUv3ORSLcyOi3QHSA+LY/KcGWiS6qAOVClBmiSnV2fMsWo6nK/x3goqYN5WNYY78mKDKv68UdRsjB9KrVc=
